# fly.toml app configuration file generated for estimate-svc on 2024-11-17T18:43:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estimate-svc'
primary_region = 'gru'

[env]
  JSON_LOG=false
  BUCKET_PHOTO='volante-order-photo'
  FORWARDED_ALLOW_IPS='*'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
